# Generated by Django 2.2 on 2020-03-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active_Member',
            new_name='ActivityPeriod',
        ),
    ]
